#!/usr/bin/bash

for ((i=1; i<=4; ++i)); do
    if [[ -z $(diff -bitw ./nfa-e-in.${i}.out ./nfa-e-in.${i}.key) ]]; then
        continue
    else 
        echo nfa-e-in.${i} "non clean diff"
    fi
done


