#!/usr/bin/bash
# Download all members of a pdse to some location
# zowe zos-files download all-members KC03AEE.CSCI360.assigns --directory . --extension .asm

if [[ $# != 4 ]]; then
    echo "Usage: ./zdd -p pdse -d directory"
    exit 1
fi
declare -a arr
while getopts 'p:d:' var; do
    arr+=($OPTARG)
done
member=${arr[0]}
directory=${arr[1]}

zowe zos-files download all-members KC03AEE.CSCI360.${member} --directory ${directory} --extension .asm


