#!/usr/bin/bash
# Zowe download single member

if [[ $# != 2 ]]; then
    echo "Usage: zdm -m member"
fi

getopts 'm:' var
member=$OPTARG

zowe zos-files download data-set "KC03AEE.CSCI360.ASSIGNS(${member})" -b -f ${member}.asm


