#!/usr/bin/bash
# List PDSE members
# zowe zos-files list all-members "KC03AEE.CSCI360.ASSIGNS"

if [[ $# != 2 ]]; then
    echo "Usage: zld -m member"
    exit 1
fi

getopts 'm:' var
zowe zos-files list all-members "KC03AEE.CSCI360.${OPTARG}"
