#!/usr/bin/bash
# Zowe list jobs

if [[ $# > 2 ]]; then
    echo "Usage: zlj [-o owner]"
fi

getopts 'o:' var
opt=$OPTARG

if [[ -z $opt ]]; then
    zowe jobs list jobs --owner "KC03AEE"
else 
    zowe jobs list jobs --owner "${opt}"
fi


# zowe jobs list jobs --owner "KC03AEE"
