#!/usr/bin/bash
# Zowe move local file to PDSE

# zowe zos-files upload file-to-data-set "assign2.asm" "kc03aee.csci360.assigns"

# -f file -p pdse

if [[ $# != 4 ]]; then
    echo "Usage: zmlf -f file -p pdse"
    exit 1
fi

declare -a arr
while getopts 'f:p:' var; do
    arr+=(${OPTARG})
done

zowe zos-files upload file-to-data-set "${arr[0]}" "KC03AEE.CSCI360.${arr[1]}"

