#!/usr/bin/bash
# Zowe move assigs PDSE member to SUBMTTD

if [[ $# != 2 ]]; then
    echo "Usage: zmts -m member"
    exit 1
fi

getopts "m:" var
member=$OPTARG

zowe zos-files copy data-set "KC03AEE.CSCI360.ASSIGNS(${member})" "KC03AEE.CSCI360.SUBMTTD"

